version: '3.5'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DATABASE: storage
      MONGO_COLLECTION: promotions
      BULK_INSERT_MAX_SIZE: 100000

    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - backend


networks:
  backend:

volumes:
  mongo: